name: rw_git
description: A git wrapper that facilitates the execution of various useful git commands.
version: 1.0.2
repository: https://github.com/gbrandtio/rw-git

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  path: ^1.8.0
  git: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
